Add failing test to test report generation on master

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -40,13 +40,20 @@ jobs:
         run: chmod +x gradlew
 
       - name: Build
-        run: ./gradlew build
+        run: ./gradlew build -x test
 
+
+      # If tests fail for a PR, the whole pipeline will fail, if we're on master branch, procceed  to reports generation
       - name: Test
-        run: ./gradlew test jacocoTestReport
+        id: test_results
+        run: |
+          ./gradlew test
+        continue-on-error: ${{ github.ref == 'refs/heads/master' }}
 
+      # Runs only on master branch regardless of previous step outcome
       - name: Deploy report
-        if: ${{ github.ref == 'refs/heads/master' }} # Run only on pushed to master
+        if: ${{ github.ref == 'refs/heads/master' }} && always()
+
         run: |
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
           git config --global user.name "Github Actions"
@@ -93,8 +100,14 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
+      - name: Process test results
+        if: steps.test_results.outcome == 'failure'
+        run: |
+          echo "Tests failed, please check the logs"
+          exit 1
+
       - name: Bump superproject commits
-        if: ${{ github.ref == 'refs/heads/master' }} # Run only on pushed to master
+        if: github.ref == 'refs/heads/master' && steps.test_results.outcome == 'success'
         run: |
           mkdir superproject
           cd superproject
@@ -107,4 +120,3 @@ jobs:
           git add backend
           git commit -m "Update commit version [skip ci]"
           git push origin master
-
